[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = ["full"] }
windows-volume-control = "0.1.1"

[dependencies.shared-data]
version = "*"
path = ".."
features = ["std"]
