[package]
name = "shared-data"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", default-features = false, features = ["derive"] }

thiserror = "1.0.61"
thiserror-no-std = "2.0.2"

[dependencies.macros]
version = "*"
path = "./macros"

[workspace]
members = ["client", "macros", "server"]

[features]
std = []
