[package]
name = "shared-data"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", default-features = false, features = ["derive"] }

[workspace]
members = ["client", "server"]
