# Makefile for cargo using cargo make

# attach probe to already running process
[tasks.attach]
dependencies = ["build"]
command = "probe-rs"
args = [
    "attach",
    "--chip",
    "STM32F401CCU6",
    "./target/thumbv7em-none-eabihf/debug/stealth577",
]

[tasks.list]
command = "probe-rs"
args = ["list"]

# [tasks.watch]
# command = "cargo"
# args = ["r", "-q"]
# watch = true
# clear = true

# [tasks.watch]
# command = "cargo"
# args = ["watch", "-q", "-c", "-x r"]

[tasks.undump]
command = "nu"
args = ["-c", "rm ./client.asm"]

[tasks.dump]
dependencies = ["build"]
command = "nu"
args = [
    "-c",
    "arm-none-eabi-objdump.exe --disassemble ../target/thumbv7em-none-eabihf/debug/client | save ./client.asm -f",
]
